openapi: 3.0.0
info:
  title: SGA
  version: '1.0'
  description: API for Smart grid analyzer
servers:
  - url: 'http://localhost:3000'
paths:
  /grid/line/ACLineSegmentPowerLosses:
    get:
      summary: Потери электроэнергии в сегменте линии
      tags:
        - Line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      ACLineSegment:
                        type: object
                        description: Сегмент линии
                        properties:
                          mRID:
                            type: string
                            description: ID
                          powerLosses:
                            $ref: '#/components/schemas/powerLosses'
              examples:
                Пример:
                  value:
                    header: {}
                    response:
                      ACLineSegment:
                        mRID: asd9sadsada
                        powerLosses:
                          phases:
                            A:
                              - value: 0.35088958366866474
                                unit: '%'
                              - value: 16800.924
                                unit: 'кв*ч'
                            B:
                              - value: 0.35088958366866474
                                unit: '%'
                              - value: 16800.924
                                unit: 'кв*ч'
                            C:
                              - value: 0.35088958366866474
                                unit: '%'
                              - value: 16800.924
                                unit: 'кв*ч'
                        total:
                          value:
                            - value: '0.35088958366866474'
                              unit: '%'
                            - value: '16800.924'
                              unit: 'кв*ч'
      operationId: get-grid-line
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID сегмента линии
      description: Метод возвращает потери электроэнергии для сегмента линии
    parameters: []
  /grid/line/linePowerLosses:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID Линии
          required: true
      tags:
        - Line
      summary: Потери электроэнергии в линии
      description: Метод возвращает потери электроэнергии для всей линии
      operationId: LinePowerLosses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      mRID:
                        type: string
                        description: ID Линиии
                      powerLosses:
                        $ref: '#/components/schemas/powerLosses'
              examples:
                Пример:
                  value:
                    header: {}
                    response:
                      mRID: 5234356546fgfg
                      powerLosses:
                        phases:
                          A:
                            - value: 0.35088958366866474
                              unit: '%'
                            - value: 16800.924
                              unit: 'кв*ч'
                          B:
                            - value: 0.35088958366866474
                              unit: '%'
                            - value: 16800.924
                              unit: 'кв*ч'
                          C:
                            - value: 0.35088958366866474
                              unit: '%'
                            - value: 16800.924
                              unit: 'кв*ч'
                      total:
                        value:
                          - value: '0.35088958366866474'
                            unit: '%'
                          - value: '16800.924'
                            unit: 'кв*ч'
    parameters: []
  /grid/consumer/energyConsumerPowerLosses:
    get:
      summary: Потери электроэнергии на абонентском участке
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      energyConsumer:
                        type: object
                        properties:
                          mRID:
                            type: string
                            description: ID Потребителя
                          powerLosses:
                            $ref: '#/components/schemas/powerLosses'
      operationId: get-grid-energy-consumer-getEnergyConsumerPowerLosses
      description: Метод возвращает потери электроэнергии на абонентском участке (отпайке)
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID потребителя
      tags:
        - EnergyConsumer
    parameters: []
  /grid/consumer/energyConsumerSubstationPowerLosses:
    get:
      summary: Потери электроэнергии от ТП до абонента
      tags:
        - EnergyConsumer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      substation:
                        type: object
                        description: Трансформаторная подстанция
                        properties:
                          mRID:
                            type: string
                      powerLosses:
                        $ref: '#/components/schemas/powerLosses'
                      energyConsumer:
                        type: object
                        description: Потребитель
                        properties:
                          mRID:
                            type: string
      operationId: get-grid-consumer-getEnergyConsumerSubstationPowerLosses
      parameters:
        - schema:
            type: string
          in: query
          name: mRIDEnergyConsumer
          description: ID потребителя
        - schema:
            type: string
          in: query
          name: mRIDSubstation
          description: ID Трансформаторной подстанции
      description: Метод возвращает потери электроэнергии на участке ТП - потребитель
    parameters: []
  /grid/substation/substationPowerLosses:
    get:
      summary: Потери электроэнергии в ТП
      tags:
        - Substation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      powerLosses:
                        type: object
                        properties:
                          total:
                            type: object
                            description: Потери в ТП
                            properties:
                              value:
                                $ref: '#/components/schemas/powerLossesValue'
                          busway:
                            type: object
                            description: Потери в шинопроводе
                            properties:
                              value:
                                $ref: '#/components/schemas/powerLossesValue'
                          powerTransformer:
                            type: object
                            description: Потери в силовом трансформаторе
                            properties:
                              value:
                                $ref: '#/components/schemas/powerLossesValue'
              examples:
                Пример:
                  value:
                    header: {}
                    response:
                      powerLosses:
                        total:
                          value:
                            - value: 16800.924
                              unit: 'кв*ч'
                            - value: 0.35088958366866474
                              unit: '%'
                        busway:
                          value:
                            - value: 16800.924
                              unit: 'кв*ч'
                            - value: 0.35088958366866474
                              unit: '%'
                        powerTransformer:
                          value:
                            - value: 16800.924
                              unit: 'кв*ч'
                            - value: 0.35088958366866474
                              unit: '%'
      operationId: get-grid-substation-get
      description: Метод возвращает потери электроэнергии в ТП (силовой трансформатор и шинопровод)
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID Трансформаторной подстанции
    parameters: []
  /grid/substation/substaionEnergyOrigination:
    get:
      summary: Количество отданной электроэнергии ТП
      operationId: get-grid-substation-getSubstaionEnergyOrigination
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      mRID:
                        type: string
                        description: ID ТП
                      powerOrigination:
                        $ref: '#/components/schemas/powerOrigination'
      tags:
        - Substation
      description: Метод возвращает количество отданной электроэнергии трансформаторной подстанцией
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID ТП
          required: true
    parameters: []
  /phasing/startEnergyConsumerPhasing:
    post:
      summary: Запустить службу определения фаз потребителей
      operationId: post-phasing-startEnergyConsumerPhasing
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/phasingWorker'
      description: Метод запускает сервис определения фаз для потребителей. Стартуют все процессы (workers)
      tags:
        - Phasing
  /phasing/result:
    get:
      summary: Результат определения фаз
      tags:
        - Phasing
        - Phasing result
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phasingResult'
      operationId: get-phasing-result
      description: Метод возвращает результат определения фаз потребителей линии
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: ID результата расчета
        - schema:
            type: string
          in: query
          name: energyConsumerMRID
          description: ID потребителя
  /phasing/result/list:
    get:
      summary: Список всех результатов определения фаз
      tags:
        - Phasing
        - Phasing result
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/phasingResult'
              examples:
                example-1: {}
      operationId: phasing-result-list
      description: Метод возвращает список с результатами определения фаз потребителей линий всей сети
      parameters:
        - schema:
            type: string
            format: date-time
          in: query
          name: date
          description: Получить список все результатов для указанной даты
    parameters: []
  /phasing/worker/list:
    get:
      summary: Список процессов определяющих фазы потребителей
      tags:
        - Phasing
        - Phasing worker
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/phasingWorker'
      operationId: get-phasing-worker-list
      description: Метод возвращает список процессов (workers) выполняющих расчет фаз потребителей для всей сети
  '/phasing/worker/metrics/{id}':
    get:
      summary: Показатели (метрики) работы процесса (worker)
      tags:
        - Phasing
        - Phasing worker
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      worker:
                        $ref: '#/components/schemas/phasingWorkerProcess'
                      metrics:
                        $ref: '#/components/schemas/phasingMetrics'
                  header:
                    type: object
                    description: Служебная информация
                required:
                  - response
              examples:
                example-1: {}
      operationId: get-phasing-statistic
      description: Метод возвращает показатели (метрики) работы процесса фазировки
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Worker ID
  /phasing/stopEnergyConsumerPhasing:
    post:
      summary: Остановить службу определения фаз потребителей
      operationId: post-phasing-stopEnergyConsumerPhasing
      responses:
        '202':
          description: Accepted
      description: Метод останавливает службу определения фаз потребителей. Будут остановлены все процессы (workers)
      parameters:
        - schema:
            type: string
          in: query
          name: reason
          description: Описание причины остановки (отмены) работающего процесса
      tags:
        - Phasing
  '/phasing/worker/{id}':
    get:
      summary: Процесс (worker) фазировки
      tags:
        - Phasing
        - Phasing worker
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                    description: Служебная информация
                  response:
                    type: object
                    properties:
                      worker:
                        $ref: '#/components/schemas/phasingWorker'
      operationId: get-phasing-worker
      description: Метод возвращает свойство процесса расчета фазировки
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID Worker
components:
  schemas:
    powerLossesValue:
      title: PowerLossesValue
      type: array
      description: Значение потерь электроэнергии
      items:
        type: object
        properties:
          value:
            type: number
            description: Значение
          unit:
            type: string
            description: Единица измерения
    phasingResult:
      title: PhasingResult
      type: object
      description: Результат определения фаз для потребителя линии
      x-tags:
        - Phasing
        - Phasing result
      properties:
        id:
          type: string
          description: ID результата
        date:
          type: string
          description: 'Дата и время, когда результат фазировки был расчитан'
          format: date-time
        line:
          type: object
          description: 'Линия, для которой выполнен алгоритм определения фаз потребителей'
          required:
            - mRID
            - energy_consumer_phasing
          properties:
            mRID:
              type: string
              description: ID Линии
            energy_consumer_phasing:
              type: array
              description: Результат фазировки для потребителя
              items:
                type: object
                properties:
                  mRID:
                    type: string
                    description: 'ID потребителя, для которого определены фазы'
                  phasing:
                    type: object
                    description: 'Растановка L1, L2, L3 потребителя по фазам'
                    required:
                      - A
                      - B
                      - C
                    properties:
                      A:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                      B:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                      C:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                  metrics:
                    type: object
                    description: Дополнительные показатели фазировки
                    properties:
                      loadBalance:
                        type: object
                        description: Доля нагрузки по фазно
                        properties:
                          A:
                            $ref: '#/components/schemas/valueUnit'
                          B:
                            $ref: '#/components/schemas/valueUnit'
                          C:
                            $ref: '#/components/schemas/valueUnit'
                required:
                  - mRID
                  - phasing
      required:
        - id
        - date
        - line
    phasingWorkerMetrics:
      title: PhasingWorker
      type: object
      x-tags:
        - Phasing
      properties:
        metrics:
          $ref: '#/components/schemas/phasingWorkerMetrics'
    phasingMetrics:
      title: PhasingWorkerMetrics
      type: object
      description: Показатели работы процесса определения фаз для потребителя линии
      properties:
        metrics:
          type: object
          properties:
            totalDuration:
              type: integer
              description: Длительность расчета в миллисекундах
            samplingDepth:
              type: integer
              description: Количество отсчетов (кол. накопленных данных)
            iterationCount:
              type: integer
              description: Количество итераций алгоритма
            overallImbalance:
              type: number
              description: '%НБ - Общий процент небаланса. 1 = 100%'
            line:
              type: object
              properties:
                mRID:
                  type: string
                  description: ID Линии
                sumByPhase:
                  type: object
                  description: 'Сумма энергий (кв*ч) фидера по фазам'
                  properties:
                    A:
                      type: number
                    B:
                      type: number
                    C:
                      type: number
                imbalanceByPhase:
                  type: object
                  description: '% небаланса по фазам'
                  properties:
                    A:
                      type: number
                    B:
                      type: number
                    C:
                      type: number
                energyConsumers:
                  type: object
                  properties:
                    sumByPhase:
                      type: object
                      description: 'Сумма энергий (кв*ч) потребителей по фазам'
                      properties:
                        A:
                          type: number
                        B:
                          type: number
                        C:
                          type: number
                    energyConsumer:
                      type: array
                      items:
                        type: object
                        properties:
                          mRID:
                            type: string
                            description: ID потребителя
                          phaseRotation:
                            type: string
                            enum:
                              - counterclockwise
                              - clockwise
                            description: 'Ротация фаз: прямая; обратная.'
                          loadBalance:
                            type: object
                            description: 'Доля нагрузки (в %) по фазам в общем потреблении'
                            properties:
                              A:
                                type: number
                              B:
                                type: number
                              C:
                                type: number
                          errors:
                            type: object
                            description: 'События (конфликты) '
                            properties:
                              columnConflict:
                                type: boolean
                                description: Конфликт по столбцам
                              incorrectPhaseRotation:
                                type: boolean
                                description: Неправильное ЧФ
                              lowLoad:
                                type: boolean
                                description: Низкая доля нагрузки
                              lowColumnCC:
                                type: boolean
                                description: Низкий КК
                              tooCloseColumnCC:
                                type: boolean
                                description: Очень близкие КК в столбце
                              rowConflict:
                                type: boolean
                                description: Конфликт по строкам
                          corrMats:
                            type: array
                            items:
                              type: number
                          phaseArrangement:
                            type: object
                            description: Растановка фаз к счетчику потребителя
                            required:
                              - was
                              - became
                            properties:
                              was:
                                type: object
                                description: Исходное соотношение входа счетчика к фазе
                                properties:
                                  A:
                                    type: string
                                  B:
                                    type: string
                                  C:
                                    type: string
                              became:
                                type: object
                                description: Определенное соотношение входа счетчика к фазе
                                properties:
                                  A:
                                    type: string
                                  B:
                                    type: string
                                  C:
                                    type: string
                        required:
                          - mRID
                          - phaseRotation
                          - loadBalance
                          - errors
                          - corrMats
                          - phaseArrangement
                    consumerWight:
                      type: array
                      description: Массив mRID потребителей - очередность перебора потребителей. Рассчитан по весу ошибок и доли нагрузки
                      items:
                        type: string
                  required:
                    - consumerWight
              required:
                - sumByPhase
            meanImbalance:
              type: number
              description: Средний небаланс
            delta:
              type: number
              description: Доверительный интервал
          required:
            - totalDuration
            - samplingDepth
            - iterationCount
            - overallImbalance
            - meanImbalance
            - delta
    phasingWorker:
      title: PhasingWorker
      type: object
      description: Процесс определяющий фазировку потребителей для линии
      properties:
        process:
          $ref: '#/components/schemas/phasingWorkerProcess'
        lineMRID:
          type: string
          format: date-time
          description: 'ID Линии, для которой процесс создан'
      x-tags:
        - Phasing worker
        - Phasing
    powerLosses:
      title: PowerLosses
      type: object
      description: Потери электроэнергии
      properties:
        phases:
          type: object
          description: Потери для каждой фазы отдельно
          properties:
            A:
              $ref: '#/components/schemas/powerLossesValue'
            B:
              $ref: '#/components/schemas/powerLossesValue'
            C:
              $ref: '#/components/schemas/powerLossesValue'
        total:
          type: object
          description: Потери для всех фаз вместе
          properties:
            value:
              $ref: '#/components/schemas/powerLossesValue'
    powerOrigination:
      title: PowerOrigination
      type: object
      properties:
        total:
          type: object
          description: Количество произведенной электроэнергии для всех фаз вместе
          properties:
            value:
              $ref: '#/components/schemas/powerOriginationValue'
        phases:
          type: object
          description: Количество произведенной электроэнергии для каждой фазы отдельно
          properties:
            A:
              $ref: '#/components/schemas/powerOriginationValue'
            B:
              $ref: '#/components/schemas/powerOriginationValue'
            C:
              $ref: '#/components/schemas/powerOriginationValue'
      description: Количество отданной электроэнергии
    powerOriginationValue:
      title: PowerOriginationValue
      type: object
      description: Количество произведенной электроэнергии
      properties:
        value:
          type: number
          description: Значение
        unit:
          type: string
          description: Единица измерения
    phasingWorkerProcess:
      title: phasingWorkerProcess
      type: object
      properties:
        id:
          type: string
          description: ID процесса
        startTime:
          type: string
          format: date-time
          description: Время старта процесса
        stopTime:
          type: string
          format: date-time
          description: Время завершения расчета для статуса Finished и время отмены для статуса Cancelled
        status:
          type: string
          description: "Статус процесса: \nRunning - Идет накопление данных;\nFinished - Расчет запущен и находится в процессе выполнения;\nCancelled - Расчет был остановлен и не доведен до конца;\nIdle - Идет накопление данных."
          enum:
            - running
            - cancelled
            - finished
            - idle
        сancelReason:
          type: string
          description: 'Причина отмены, если процесс расчета фаз был отменен (статус cancelled)'
      description: Worker - процесс выполняющий работу по определению фаз потребителя
      x-tags:
        - Phasing worker
        - Phasing
    valueUnit:
      title: valueUnit
      type: object
      description: Значение и в чем оно измеряется
      properties:
        value:
          type: string
          description: Значение
        unit:
          type: string
          description: Единица измерения
